### ISSUE TITLE
No such file or directory: static.html

### ISSUE THREAD

**Issue by ZiYang-oyxy** [tweekmonster/tmux2html#13]
```bash
$ tmux2html 0
Traceback (most recent call last):
  File "/home/oyxy/.local/bin/tmux2html", line 9, in <module>
    load_entry_point('tmux2html==0.1.11', 'console_scripts', 'tmux2html')()
  File "/home/oyxy/.local/lib/python2.7/site-packages/tmux2html/main.py", line 798, in main
    max_lines=args.history)
  File "/home/oyxy/.local/lib/python2.7/site-packages/tmux2html/main.py", line 531, in render_pane
    interval=script_reload)
  File "/home/oyxy/.local/lib/python2.7/site-packages/tmux2html/tpl.py", line 22, in render
    return load(name).safe_substitute(**kwargs)
  File "/home/oyxy/.local/lib/python2.7/site-packages/tmux2html/tpl.py", line 15, in load
    with open(os.path.join(_basedir, 'templates', name), 'rt') as fp:
IOError: [Errno 2] No such file or directory: u'/home/oyxy/.local/lib/python2.7/site-packages/tmux2html/templates/static.html'
```

How to fix it?

**Comment by ZiYang-oyxy** [comment]
My installation is wrong. I fix it by myself.
Close it now.
